### ISSUE TITLE
操作手册能详细些么

### ISSUE THREAD

**Issue by a5825799** [holo-routing/holo#5]
能有个 基于 docker 或者其他 搭出的最小demo 么，什么都不了解的情况下没有办法入手。

**Comment by rwestphal** [comment]
Hi @a5825799,

Sure. The easiest way to get started with the project is to use the following containerlab topologies: https://github.com/rwestphal/containerlab-topologies

With a single command you can start an entire virtual topology and get a hands-on experience with *holod* and *holo-cli*. You can even test interoperability against other implementations (FRR, Nokia, Arista, etc).

If you have any questions, please feel free to join our [Discord channel](https://discord.gg/deqkRvhHB9).
