### ISSUE TITLE
holod crash on "show state"

### ISSUE THREAD

**Issue by mattiaswal** [holo-routing/holo#6]
<pre>
lazzer@tollan ~/Documents/holo (master)$ ./target/release/holo-cli 
holo# show running  (empty)
holo# show  state 
thread 'tokio-runtthread 'main' panicked at holo-cli/src/client/grpc.rs:181:14:hbound/src/state.rs:995:21:
Failed to parse gRPC Get() response: Status { code: Unknown, message: "transport error", source: Some(tonic::transport::Error(Transport, hyper::Error(Io, Custom { kind: BrokenPipe, error: "stream closed because of a broken pipe" }))) }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]+  Exit 1                  sudo ./target/release/holod

</pre>

**Comment by rwestphal** [comment]
@mattiaswal As of now, `Get()` requests with empty paths are not supported. This and other limitations should be addressed in the near future as I'm planning to do a major rework in the northbound framework for state retrieval. In the meanwhile, I have added a workaround to prevent *holod* from crashing when an empty `Get()` is received, returning an error to the client instead. Thanks for reporing this problem.
