### ISSUE TITLE
Are you aware of Holo Hosting?

### ISSUE THREAD

**Issue by timotree3** [holo-routing/holo#8]
Hi, this seems like a cool project! I just wanted to link you to Holo (https://holo.host/), which is a tech project using the same name. They're doing hosting and you're doing routing, but those two domains seem pretty adjacent to me.

I'm not personally requesting you change the name or anything, but I thought you should be informed sooner than later while it might still be possible to change the name without losing too much recognition.

**Comment by rwestphal** [comment]
@timotree3 Thanks for bringing that to my attention. At one point I became aware of holochain, but I didn't know it was connected to another project called Holo.

While I agree there's some potential for confusion, renaming the project would be difficult and unlikely to happen at this point. Nonetheless, I will discuss this matter with other people and carefully consider all options.

Thank you for your understanding.
